const bookingHeadText = [
    { "en" : "Hey, are you free to DJ on <START_DATE>?" },
    { "en" : "Hi, are you available for a gig on <START_DATE>?" },
    { "en" : "Are you open to DJ on <START_DATE>?" },
    { "en" : "Can you play a set on <START_DATE>?" },
    { "en" : "Are you around to DJ on <START_DATE>?" },
    { "en" : "Can you DJ on <START_DATE>?" },
    { "en" : "Are you free to perform on <START_DATE>?" },
    { "en" : "Can I book you to DJ on <START_DATE>?" },
    { "en" : "Are you available to DJ for an event on <START_DATE>?" },
    { "en" : "Would you be able to play on <START_DATE>?" },
    { "en" : "Can you take a gig on <START_DATE>?" },
    { "en" : "Are you free for a DJ set on <START_DATE>?" },
    { "en" : "Can we book you for <START_DATE>?" },
    { "en" : "Would you be able to perform on <START_DATE>?" },
    { "en" : "Are you available for a set on <START_DATE>?" },
    { "en" : "Can you perform as a DJ on <START_DATE>?" },
    { "en" : "Would you be up for DJing on <START_DATE>?" },
    { "en" : "Is <START_DATE> free for you to DJ?" },
    { "en" : "Can we lock you in for a DJ set on <START_DATE>?" },
    { "en" : "Do you have availability to DJ on <START_DATE>?" },
    { "en" : "Could you play as our DJ on <START_DATE>?" },
    { "en" : "Would you be interested in DJing on <START_DATE>?" },
    { "en" : "Do you have a spot open to DJ on <START_DATE>?" },
    { "en" : "Are you available to perform a set on <START_DATE>?" },
    { "en" : "Could you spin some tracks on <START_DATE>?" },
    { "en" : "Are you down to DJ on <START_DATE>?" },
    { "en" : "Could you DJ at our party on <START_DATE>?" },
    { "en" : "Can we book you on <START_DATE> to DJ?" },
    { "en" : "Are you available to DJ on the evening of <START_DATE>?" },
    { "en" : "Would you be free to DJ our event happening on <START_DATE>?" },
    { "en" : "On <START_DATE>, would you be able to DJ for us?" },
    { "en" : "Can we have you DJ on <START_DATE>?" },
    { "en" : "What's your availability like for DJing on <START_DATE>?" },
    { "en" : "Could you perform as a DJ at our event on <START_DATE>?" },
    { "en" : "Will you be available to DJ on <START_DATE>?" },
    { "en" : "On <START_DATE>, would you be able to spin for us?" },
    { "en" : "Are you free to DJ an event on <START_DATE>?" },
    { "en" : "Do you have any availability to DJ on <START_DATE>?" },
    { "en" : "Can you fit in a DJ gig on <START_DATE>?" },
    { "en" : "Are you available for a DJ gig on <START_DATE>?" },
    { "en" : "Can you perform a set on <START_DATE>?" },
    { "en" : "How's your schedule looking for DJing on <START_DATE>?" },
    { "en" : "Do you have time to DJ on the night of <START_DATE>?" },
    { "en" : "Are you free to take a DJ gig on <START_DATE>?" },
    { "en" : "Can we count on you for a DJ set on <START_DATE>?" },
    { "en" : "Would you be able to join us as a DJ on <START_DATE>?" },
    { "en" : "Can we lock you in to DJ on <START_DATE>?" },
    { "en" : "Would you be up for spinning on <START_DATE>?" },
    { "en" : "Is <START_DATE> available on your calendar to DJ?" },
    { "en" : "Are you open to DJing for us on <START_DATE>?" },
    { "en" : "Do you have a slot open to DJ on <START_DATE>?" },
    { "en" : "Can we book you to play music on <START_DATE>?" },
    { "en" : "Would you be interested in doing a DJ set on <START_DATE>?" },
    { "en" : "Could we get you to DJ for our event on <START_DATE>?" },
    { "en" : "Is <START_DATE> a good day for you to DJ for us?" },
    { "en" : "Would it be possible for you to DJ at our event on <START_DATE>?" },
    { "en" : "Could you work a DJ gig on <START_DATE>?" },
    { "en" : "On <START_DATE>, would you be available to take on a DJ set?" },
    { "en" : "Can you commit to DJing on <START_DATE>?" },
    { "en" : "Would you be available to play some tunes on <START_DATE>?" },
    { "en" : "Are you available to DJ for a party on <START_DATE>?" },
    { "en" : "Is there any chance you could DJ on <START_DATE>?" },
    { "en" : "How's your schedule looking for a DJ set on <START_DATE>?" },
    { "en" : "Do you have a slot open to perform as a DJ on <START_DATE>?" },
    { "en" : "Could you join us to DJ on <START_DATE>?" },
    { "en" : "Are you available to spin at our event on <START_DATE>?" },
    { "en" : "Would you be interested in taking a DJ gig on <START_DATE>?" },
    { "en" : "Would it work for you to DJ at our event on <START_DATE>?" },
    { "en" : "On <START_DATE>, are you available to DJ?" },
    { "en" : "Could you make it for a DJ set on <START_DATE>?" },
    { "en" : "What's your availability for DJing on <START_DATE>?" },
    { "en" : "Could we count on you to DJ our event on <START_DATE>?" },
    { "en" : "Can you do a DJ set for us on <START_DATE>?" },
    { "en" : "Do you have an opening to DJ on <START_DATE>?" },
    { "en" : "Would you have time to DJ for us on <START_DATE>?" },
    { "en" : "Are you able to take on a DJ gig on <START_DATE>?" },
    { "en" : "Can you play at our event on <START_DATE> as the DJ?" },
    { "en" : "Are you available to DJ a party on <START_DATE>?" },
    { "en" : "How's your availability for DJing on <START_DATE>?" },
    { "en" : "Can we count on you for a DJ performance on <START_DATE>?" },
    { "en" : "Would you be up for DJing at our event on <START_DATE>?" },
    { "en" : "Can you handle a DJ set on <START_DATE>?" },
    { "en" : "Is there any chance you're free to DJ on <START_DATE>?" },
    { "en" : "Could we book you as the DJ on <START_DATE>?" },
    { "en" : "Can you take a DJ gig for our event on <START_DATE>?" },
    { "en" : "Could you do us the honor of DJing on <START_DATE>?" },
    { "en" : "Can you be the DJ for our event on <START_DATE>?" },
    { "en" : "Would <START_DATE> work for you to take a DJ gig?" },
    { "en" : "Could you be our DJ on <START_DATE> for a special event?" },
    { "en" : "Are you available to spin for a crowd on <START_DATE>?" },
    { "en" : "Can we book you as our DJ on <START_DATE>?" },
    { "en" : "Is it possible for you to perform a DJ set on <START_DATE>?" },
    { "en" : "Could we schedule you to DJ on <START_DATE>?" },
    { "en" : "Would you be able to DJ for our event on <START_DATE>?" },
    { "en" : "Can you DJ for our party on <START_DATE>?" },
    { "en" : "Are you open to performing a set on <START_DATE>?" },
    { "en" : "Is there a chance you could DJ for us on <START_DATE>?" },
    { "en" : "Are you free to DJ a special event on <START_DATE>?" },
    { "en" : "Would you be able to make it to DJ on <START_DATE>?" },
    { "en" : "Can you take over the DJ booth on <START_DATE>?" },
    { "en" : "Can we reserve you for DJing on <START_DATE>?" },
    { "en" : "Can we count on you to spin some music on <START_DATE>?" },
    { "en" : "Do you have a free spot to DJ on <START_DATE>?" },
    { "en" : "Are you open to doing a DJ gig on <START_DATE>?" },
    { "en" : "Would you be able to provide music on <START_DATE> as the DJ?" },
    { "en" : "Could you block out <START_DATE> to DJ for us?" },
    { "en" : "Are you available to DJ for an event happening on <START_DATE>?" },
    { "en" : "Do you have time for a DJ gig on <START_DATE>?" },
    { "en" : "Is it possible for you to DJ a set on <START_DATE>?" },
    { "en" : "Can you perform as our DJ on <START_DATE>?" },
    { "en" : "Would you be able to take a DJ job on <START_DATE>?" },
    { "en" : "Are you free to handle the music on <START_DATE>?" },
    { "en" : "Can we lock you in to DJ for a party on <START_DATE>?" },
    { "en" : "Could you take a DJ spot for us on <START_DATE>?" },
    { "en" : "Would you be up for covering a DJ set on <START_DATE>?" },
    { "en" : "Is your schedule free for DJing on <START_DATE>?" },
    { "en" : "Could you be our DJ on <START_DATE> for a gig?" },
    { "en" : "Would you be able to perform at our event as a DJ on <START_DATE>?" },
    { "en" : "Is <START_DATE> open for a DJ gig with you?" },
    { "en" : "Can you make it as the DJ for our event on <START_DATE>?" },
    { "en" : "Are you able to take on a DJ set on <START_DATE>?" },
    { "en" : "Could we schedule a DJ set with you on <START_DATE>?" },
    { "en" : "Can we count on you to DJ the event on <START_DATE>?" },
    { "en" : "Are you available to spin tracks for us on <START_DATE>?" },
    { "en" : "Can we secure you as the DJ on <START_DATE>?" },
    { "en" : "Would you be open to performing as a DJ on <START_DATE>?" },
    { "en" : "Can you cover the music on <START_DATE> as the DJ?" },
    { "en" : "Are you able to take a DJ gig for our event on <START_DATE>?" },
    { "en" : "Would <START_DATE> work for you to DJ at our party?" },
    { "en" : "Could you perform at our event as a DJ on <START_DATE>?" },
    { "en" : "Can we schedule a performance with you as DJ on <START_DATE>?" },
    { "en" : "Do you have any availability for DJing on <START_DATE>?" },
    { "en" : "Would you be up for spinning for us on <START_DATE>?" },
    { "en" : "Can we get you to DJ the party on <START_DATE>?" },
    { "en" : "Is <START_DATE> good for you to DJ at our event?" },
    { "en" : "Are you available to spin for an event on <START_DATE>?" },
    { "en" : "Can you DJ for a special occasion on <START_DATE>?" },
    { "en" : "Do you have an opening to DJ our event on <START_DATE>?" },
    { "en" : "Could you take a DJ slot on <START_DATE> for us?" },
    { "en" : "Are you free to handle the DJ booth on <START_DATE>?" },
    { "en" : "Can you lock in <START_DATE> to DJ at our event?" },
    { "en" : "Would you be able to take over the music on <START_DATE> as the DJ?" },
    { "en" : "Are you available to take a DJ gig on <START_DATE>?" },
    { "en" : "Can you play a DJ set on <START_DATE>?" },
    { "en" : "Do you have time to DJ on <START_DATE>?" },
    { "en" : "Could you take on a DJ role for us on <START_DATE>?" },
    { "en" : "Can you set aside <START_DATE> to DJ for us?" },
    { "en" : "Would you be available to handle the DJ duties on <START_DATE>?" },
    { "en" : "Can we book you for a DJ set on <START_DATE>?" },
    { "en" : "Is it possible for you to perform as a DJ on <START_DATE>?" },
    { "en" : "Could you fit us into your schedule to DJ on <START_DATE>?" },
    { "en" : "Can you be our DJ on <START_DATE>?" },
    { "en" : "Would you be able to perform a DJ set at our event on <START_DATE>?" },
    { "en" : "Can you set aside <START_DATE> to DJ at our event?" },
    { "en" : "Would you have availability to DJ on <START_DATE>?" },
    { "en" : "Is <START_DATE> free for you to perform a DJ set?" },
    { "en" : "Could we book you to DJ our event on <START_DATE>?" },
    { "en" : "Would <START_DATE> work for you to DJ for us?" },
    { "en" : "Are you free to DJ on <START_DATE> for our event?" },
    { "en" : "Would you be able to DJ at our function on <START_DATE>?" },
    { "en" : "Are you open to taking a DJ job on <START_DATE>?" },
    { "en" : "Could you make time to DJ on <START_DATE>?" },
    { "en" : "Can you accommodate a DJ gig on <START_DATE>?" },
    { "en" : "Can we book you to play a DJ set on <START_DATE>?" },
    { "en" : "Could we arrange for you to perform as a DJ on <START_DATE>?" },
    { "en" : "Could you take time on <START_DATE> to be our DJ?" },
    { "en" : "Would you be available to DJ a special event on <START_DATE>?" },
    { "en" : "Is <START_DATE> good for you to take on a DJ role?" },
    { "en" : "Could we book you for a DJ performance on <START_DATE>?" },
    { "en" : "Would you be able to handle the DJ duties on <START_DATE>?" },
    { "en" : "Is there a chance you could DJ on <START_DATE>?" },
    { "en" : "Can we schedule you for a DJ set on <START_DATE>?" },
    { "en" : "Could we reserve you to DJ on <START_DATE>?" },
    { "en" : "Would you have time to perform a DJ set on <START_DATE>?" },
    { "en" : "Can you set aside <START_DATE> for a DJ gig?" },
    { "en" : "Is <START_DATE> available for you to take on a DJ slot?" },
    { "en" : "Would you be free to handle the DJing on <START_DATE>?" },
    { "en" : "Can we book you to provide music on <START_DATE>?" },
    { "en" : "Are you able to DJ for us on <START_DATE>?" },
    { "en" : "Could you fit us into your schedule for a DJ set on <START_DATE>?" },
    { "en" : "Is it possible for you to DJ on <START_DATE>?" },
    { "en" : "Can we arrange for you to take a DJ role on <START_DATE>?" },
    { "en" : "Are you free to spin on <START_DATE> for our event?" },
    { "en" : "Would you be available for a DJ gig on <START_DATE>?" },
    { "en" : "Can we rely on you to DJ on <START_DATE>?" },
    { "en" : "Could you cover the DJ slot on <START_DATE>?" },
    { "en" : "Can you make it for a DJ gig on <START_DATE>?" },
    { "en" : "Would you be free to handle the DJ set on <START_DATE>?" },
    { "en" : "Could you DJ for us on <START_DATE>?" },
    { "en" : "Is there a chance you could perform as a DJ on <START_DATE>?" },
    { "en" : "Can you fit us in for a DJ gig on <START_DATE>?" },
    { "en" : "Could we book you for a DJ slot on <START_DATE>?" },
    { "en" : "Would you be able to take on a DJ gig on <START_DATE>?" },
    { "en" : "Can you cover a DJ role for us on <START_DATE>?" },
    { "en" : "Would you be free to DJ at our party on <START_DATE>?" },
    { "en" : "Is <START_DATE> open for a DJ performance from you?" },
    { "en" : "Can we reserve you to DJ on <START_DATE>?" },
    { "en" : "Could you fit a DJ set into your schedule on <START_DATE>?" },
    { "en" : "Are you open to DJing at our event on <START_DATE>?" },
    { "en" : "Would <START_DATE> be a good day for you to DJ?" },
    { "en" : "Could you handle the DJ duties on <START_DATE>?" },
    { "en" : "Are you free for a DJ gig on <START_DATE>?" },
    { "en" : "Would you be available to perform as a DJ on <START_DATE>?" },
    { "en" : "Can you set aside <START_DATE> for a DJ performance?" },
    { "en" : "Could you make it to DJ at our event on <START_DATE>?" },
    { "en" : "Are you free to cover a DJ set on <START_DATE>?" },
    { "en" : "Would you be able to fit us into your DJ schedule on <START_DATE>?" },
    { "en" : "Can you handle the music on <START_DATE> as our DJ?" },
    { "en" : "Is <START_DATE> available for you to perform a DJ gig?" },
    { "en" : "Can we schedule you to DJ at our event on <START_DATE>?" },
    { "en" : "Can you make time on <START_DATE> to handle a DJ set?" },
    { "en" : "Could you be available to DJ for us on <START_DATE>?" },
    { "en" : "Is <START_DATE> a good time for you to take a DJ slot?" },
    { "en" : "Could you manage a DJ gig on <START_DATE>?" },
    { "en" : "Can you take on a DJ role on <START_DATE>?" },
    { "en" : "Are you available for a DJ set on <START_DATE>?" },
    { "en" : "Can we secure you for a DJ performance on <START_DATE>?" },
    { "en" : "Could you cover a DJ slot for us on <START_DATE>?" },
    { "en" : "Can you dedicate <START_DATE> to be our DJ?" },
    { "en" : "Would <START_DATE> work for you to DJ at our event?" },
    { "en" : "Can we book you for a DJ performance on <START_DATE>?" },
    { "en" : "Would you have time to perform as a DJ on <START_DATE>?" },
    { "en" : "Are you available to take on a DJ role on <START_DATE>?" },
    { "en" : "Could you be available to DJ on <START_DATE>?" },
    { "en" : "Are you free to spin for us on <START_DATE>?" },
    { "en" : "Could you set aside <START_DATE> for a DJ performance?" },
    { "en" : "Is <START_DATE> a good date for you to DJ?" },
    { "en" : "Are you available to DJ on <START_DATE> for our gathering?" },
    { "en" : "Would you be free to take on a DJ gig on <START_DATE>?" },
    { "en" : "Could we reserve you to DJ for us on <START_DATE>?" },
    { "en" : "Is <START_DATE> open for you to perform a DJ set?" },
    { "en" : "Are you free to provide DJ services on <START_DATE>?" },
    { "en" : "Can we count on you to DJ at our event on <START_DATE>?" },
    { "en" : "Could you manage a DJ set on <START_DATE>?" },
    { "en" : "Would <START_DATE> work for you to handle a DJ gig?" },
    { "en" : "Are you available to spin at our party on <START_DATE>?" },
    { "en" : "Is <START_DATE> a good time for you to take a DJ gig?" },
    { "en" : "Can we arrange for you to DJ our event on <START_DATE>?" },
    { "en" : "Could you cover a DJ slot on <START_DATE>?" },
    { "en" : "Can you dedicate <START_DATE> to DJ for us?" },
    { "en" : "Are you available to handle a DJ role on <START_DATE>?" },
    { "en" : "Can we book you to spin on <START_DATE>?" },
    { "en" : "Is <START_DATE> good for you to DJ?" },
    { "en" : "Can we schedule a DJ gig with you on <START_DATE>?" },
    { "en" : "Can we count on you to handle the DJing on <START_DATE>?" },
    { "en" : "Are you available to spin for us on <START_DATE>?" },
    { "en" : "Could you make it to DJ our event on <START_DATE>?" },
    { "en" : "Can you be available for a DJ performance on <START_DATE>?" },
    { "en" : "Would you be able to fit a DJ gig into your schedule on <START_DATE>?" },
    { "en" : "Are you open to DJing on <START_DATE>?" },
    { "en" : "Can we book you to perform a DJ set on <START_DATE>?" },
    { "en" : "Would you be free to handle the DJ duties on <START_DATE>?" },
    { "en" : "Can you fit us into your schedule for a DJ set on <START_DATE>?" },
    { "en" : "Are you available to DJ on <START_DATE> for a special event?" },
    { "en" : "Would <START_DATE> work for you to DJ?" },
    { "en" : "Can we book you to handle a DJ gig on <START_DATE>?" },
    { "en" : "Could you fit a DJ role into your schedule on <START_DATE>?" },
    { "en" : "Can you handle the DJing on <START_DATE>?" },
    { "en" : "Are you available to DJ at our event on <START_DATE>?" },
    { "en" : "Would you be available to provide a DJ performance on <START_DATE>?" },
    { "en" : "Can we reserve you for a DJ gig on <START_DATE>?" },
    { "en" : "Are you free to handle the DJ duties on <START_DATE>?" },
    { "en" : "Can you perform as a DJ on <START_DATE> for us?" },
    { "en" : "Could you take on a DJ slot on <START_DATE>?" },
    { "en" : "Are you available to DJ on <START_DATE> for us?" },
    { "en" : "Can we schedule you for a DJ performance on <START_DATE>?" },
    { "en" : "Would you have time to DJ on <START_DATE>?" },
    { "en" : "Could you handle a DJ gig on <START_DATE>?" },
    { "en" : "Can you dedicate <START_DATE> to perform a DJ set for us?" },
    { "en" : "Are you free to spin on <START_DATE>?" },
    { "en" : "Can you handle a DJ slot on <START_DATE>?" },
    { "en" : "Are you available to take a DJ role on <START_DATE>?" },
    { "en" : "Can we reserve you for a DJ set on <START_DATE>?" },
    { "en" : "Can you cover a DJ gig on <START_DATE>?" },
    { "en" : "Would you be able to perform as our DJ on <START_DATE>?" },
    { "en" : "Can we book you to provide DJ services on <START_DATE>?" },
    { "en" : "Are you open to a DJ set on <START_DATE>?" },
    { "en" : "Can you fit a DJ performance into your calendar on <START_DATE>?" },
    { "en" : "Are you free to perform a DJ set on <START_DATE>?" },
    { "en" : "Can we count on you to handle a DJ gig on <START_DATE>?" },
    { "en" : "Would you be able to DJ for us on <START_DATE>?" },
    { "en" : "Can you make time to DJ on <START_DATE>?" },
    { "en" : "Is <START_DATE> good for you to take a DJ slot?" },
    { "en" : "Can we book you to DJ at our party on <START_DATE>?" },
    { "en" : "Could you take a DJ role on <START_DATE>?" },
    { "en" : "Are you available to handle the DJing on <START_DATE>?" },
    { "en" : "Can we arrange for you to DJ on <START_DATE>?" },
    { "en" : "Would you be available to take on a DJ gig on <START_DATE>?" },
    { "en" : "Are you free to DJ for us on <START_DATE>?" },
    { "en" : "Could you perform a DJ set on <START_DATE>?" },
    { "en" : "Are you open to performing as a DJ on <START_DATE>?" },
    { "en" : "Can you fit us into your schedule for DJing on <START_DATE>?" },
    { "en" : "Could you handle a DJ slot on <START_DATE>?" },
    { "en" : "Can you make time to spin at our event on <START_DATE>?" },
    { "en" : "Is <START_DATE> a good day for you to DJ?" },
    { "en" : "Could you be our DJ for the event on <START_DATE>?" },
    { "en" : "Would you be available to handle a DJ gig on <START_DATE>?" },
    { "en" : "Can you make it to DJ on <START_DATE>?" },
    { "en" : "Are you free to DJ at our event on <START_DATE>?" },
    { "en" : "Can we arrange for you to perform a DJ set on <START_DATE>?" },
    { "en" : "Could you take on a DJ gig on <START_DATE>?" },
    { "en" : "Can you cover the DJ duties on <START_DATE>?" },
    { "en" : "Is <START_DATE> a good time for you to DJ?" },
    { "en" : "Would you be able to handle a DJ set on <START_DATE>?" },
    { "en" : "Is <START_DATE> available for a DJ performance from you?" },
    { "en" : "Are you open to a DJ gig on <START_DATE>?" },
    { "en" : "Would you be available to DJ on <START_DATE> for us?" },
    { "en" : "Can we schedule you to perform a DJ set on <START_DATE>?" },
    { "en" : "Are you available to handle the DJ duties on <START_DATE>?" },
    { "en" : "Can you take on a DJ gig on <START_DATE>?" },
    { "en" : "Can we book you to provide a DJ performance on <START_DATE>?" },
    { "en" : "Would <START_DATE> work for you to be our DJ?" },
    { "en" : "Can you dedicate <START_DATE> to DJing for us?" },
    { "en" : "Could you fit a DJ gig into your schedule on <START_DATE>?" },
    { "en" : "Can we count on you to provide DJ services on <START_DATE>?" },
    { "en" : "Would you be able to DJ our event on <START_DATE>?" },
    { "en" : "Can you cover a DJ performance on <START_DATE>?" },
    { "en" : "Is <START_DATE> open for a DJ set from you?" },
    { "en" : "Can we secure you for a DJ gig on <START_DATE>?" },
    { "en" : "Are you available to DJ on <START_DATE> for a special occasion?" },
    { "en" : "Can you make it for a DJ set on <START_DATE>?" },
    { "en" : "Could you handle the DJing on <START_DATE>?" },
    { "en" : "Are you free to take a DJ slot on <START_DATE>?" },
    { "en" : "Can we book you to DJ at our event on <START_DATE>?" },
    { "en" : "Would you be available to DJ on <START_DATE>?" },
    { "en" : "Can you take a DJ slot on <START_DATE>?" },
    { "en" : "Would you be available to perform a DJ set on <START_DATE>?" },
    { "en" : "Can we schedule you to DJ on <START_DATE>?" },
    { "en" : "Are you free for a DJ performance on <START_DATE>?" },
    { "en" : "Could you handle the DJ gig on <START_DATE>?" },
    { "en" : "Are you open to spinning at our event on <START_DATE>?" },
    { "en" : "Can you make time to DJ for us on <START_DATE>?" },
    { "en" : "Could you fit a DJ performance into your schedule on <START_DATE>?" },
    { "en" : "Can we arrange for you to DJ at our party on <START_DATE>?" },
    { "en" : "Are you free to handle a DJ set on <START_DATE>?" },
    { "en" : "Would you be able to provide DJ services on <START_DATE>?" },
    { "en" : "Can you dedicate <START_DATE> to DJ for our event?" },
    { "en" : "Are you available to cover a DJ slot on <START_DATE>?" },
    { "en" : "Can we schedule a DJ performance with you on <START_DATE>?" },
    { "en" : "Can you manage a DJ gig on <START_DATE>?" },
    { "en" : "Can we book you to handle the DJing on <START_DATE>?" },
    { "en" : "Would you be able to fit a DJ performance into your schedule on <START_DATE>?" },
    { "en" : "Is <START_DATE> open for a DJ set with you?" },
    { "en" : "Can you cover a DJ role on <START_DATE>?" },
    { "en" : "Are you free to DJ at our gathering on <START_DATE>?" },
    { "en" : "Can we secure your DJ services for <START_DATE>?" },
    { "en" : "Could you handle a DJ set on <START_DATE>?" },
    { "en" : "Can you make it to DJ our event on <START_DATE>?" },
    { "en" : "Would <START_DATE> work for you to perform a DJ set?" },
    { "en" : "Can we schedule you for a DJ gig on <START_DATE>?" },
    { "en" : "Are you free to perform as a DJ on <START_DATE>?" },
    { "en" : "Can you take on a DJ performance on <START_DATE>?" },
    { "en" : "Would you be available for a DJ role on <START_DATE>?" },
    { "en" : "Can we book you for a DJ session on <START_DATE>?" },
    { "en" : "Can you handle a DJ gig for us on <START_DATE>?" },
    { "en" : "Are you available to DJ at our party on <START_DATE>?" },
    { "en" : "Can you fit a DJ slot into your schedule on <START_DATE>?" },
    { "en" : "Could we arrange for you to DJ on <START_DATE>?" },
    { "en" : "Can we count on you to handle the DJ duties on <START_DATE>?" },
    { "en" : "Would you be free to DJ on <START_DATE>?" },
    { "en" : "Are you available to take on a DJ set on <START_DATE>?" },
    { "en" : "Can we book you to DJ our event on <START_DATE>?" },
    { "en" : "Could you fit us into your schedule for a DJ gig on <START_DATE>?" },
    { "en" : "Can you make time to perform as a DJ on <START_DATE>?" },
    { "en" : "Is <START_DATE> a good day for you to handle a DJ set?" },
    { "en" : "Can we secure your services to DJ on <START_DATE>?" },
    { "en" : "Would you be able to DJ at our event on <START_DATE>?" },
    { "en" : "Can you cover a DJ slot on <START_DATE>?" },
    { "en" : "Are you available to handle a DJ set on <START_DATE>?" },
    { "en" : "Can we book you to DJ on <START_DATE>?" },
    { "en" : "Could you take on a DJ role on <START_DATE>?" },
    { "en" : "Is <START_DATE> open for you to perform a DJ gig?" },
    { "en" : "Can you handle a DJ gig on <START_DATE>?" },
    { "en" : "Are you free to spin at our event on <START_DATE>?" },
    { "en" : "Would <START_DATE> work for you to DJ our event?" },
    { "en" : "Can we book you to handle a DJ set on <START_DATE>?" },
    { "en" : "Could you cover a DJ gig on <START_DATE>?" },
    { "en" : "Can you manage a DJ slot on <START_DATE>?" },
    { "en" : "Are you available to DJ on <START_DATE>?" },
    { "en" : "Can we secure your services to perform a DJ set on <START_DATE>?" },
    { "en" : "Would you be able to DJ on <START_DATE> for us?" },
    { "en" : "Can you take a DJ role on <START_DATE>?" },
    { "en" : "Is <START_DATE> available for you to DJ?" },
    { "en" : "Can you fit us into your DJ schedule on <START_DATE>?" },
    { "en" : "Are you free to cover a DJ gig on <START_DATE>?" },
    { "en" : "Can we schedule you to DJ at our party on <START_DATE>?" },
    { "en" : "Would you be available to DJ for us on <START_DATE>?" },
    { "en" : "Can you handle the DJ duties on <START_DATE>?" },
    { "en" : "Is <START_DATE> a good date for you to perform a DJ set?" },
    { "en" : "Can we book you for a DJ slot on <START_DATE>?" },
    { "en" : "Could you be our DJ on <START_DATE>?" },
    { "en" : "Can you make time to DJ our event on <START_DATE>?" },
    { "en" : "Are you available for a DJ performance on <START_DATE>?" },
    { "en" : "Can we count on you to DJ on <START_DATE>?" },
    { "en" : "Would you be free to handle a DJ gig on <START_DATE>?" },
    { "en" : "Can you dedicate <START_DATE> to a DJ performance?" },
    { "en" : "Is <START_DATE> open for you to DJ?" },
    { "en" : "Can we schedule a DJ set with you on <START_DATE>?" },
    { "en" : "Are you available to perform as a DJ on <START_DATE>?" },
    { "en" : "Can you manage a DJ performance on <START_DATE>?" },
    { "en" : "Could we reserve you for a DJ set on <START_DATE>?" },
    { "en" : "Can you handle a DJ role on <START_DATE>?" },
    { "en" : "Would you be available to DJ at our event on <START_DATE>?" },
    { "en" : "Can we book you for a DJ gig on <START_DATE>?" },
    { "en" : "Are you open to performing a DJ set on <START_DATE>?" },
    { "en" : "Can you fit a DJ role into your schedule on <START_DATE>?" },
    { "en" : "Could you take on a DJ performance on <START_DATE>?" },
    { "en" : "Is <START_DATE> a good day for you to handle a DJ gig?" },
    { "en" : "Can we count on you to provide a DJ set on <START_DATE>?" },
    { "en" : "Are you free to DJ on <START_DATE>?" },
    { "en" : "Can we schedule you to handle a DJ gig on <START_DATE>?" },
    { "en" : "Would you be available for a DJ performance on <START_DATE>?" },
    { "en" : "Can you fit a DJ performance into your schedule on <START_DATE>?" }
]